name: Android build

on:
  push:
    branches: [ main, '@kwasow/CI' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v3

      - name: ðŸ— Enable corepack
        run: corepack enable

      - name: ðŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: ðŸ“¦ Install dependencies
        run: yarn install
      
      - name: ðŸ”‘ Inject secrets
        run: echo $GOOGLE_SERVICES_JSON > google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: ðŸš€ Build app
        run: npx expo prebuild --platform android && npx react-native build-android
