name: iOS build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: ğŸ— Enable corepack
        run: corepack enable

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: â— Restore build cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ios
          key: build-ios-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            build-ios-${{ runner.os }}-

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: ğŸ”„ Clear Derived Data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ios/Pods
          rm -rf ios/build

      - name: ğŸ”§ Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: ğŸš€ Build app
        run: |
          sudo xcode-select --switch /Applications/Xcode_16.1.app/Contents/Developer
          npx expo prebuild --platform ios
          cd ios
          set -o pipefail && xcodebuild -workspace pixelfed.xcworkspace -scheme Pixelfed -destination "platform=iOS Simulator,name=iPhone SE (3rd generation)" | xcbeautify --renderer github-actions
